name: Run tests and upload coverage

on: 
  push

jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    env:  
      VITE_SUPABASE_URL: "http://localhost:54321"
      VITE_SUPABASE_ANON_KEY: "dummy-key"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Install backend dependencies
        run: cd backend && npm install

      - name: Go back to root
        run: cd ..


      - name: Run tests
        run: npx jest --coverage --passWithNoTests --detectOpenHandles

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: DolfShungube/Hiking-Logbook
